apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-action-deployment
  labels:
    app: github-action-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-action-deployment
  template:
    metadata:
      labels:
        app: github-action-deployment
    spec:
      containers:
        - name: github-action-deployment
          image: "public.ecr.aws/j4m1p3o4/github_action:1.0"
          imagePullPolicy: AlwaysS
          ports:
            - containerPort: 8080