apiVersion: apps/v1
kind: Deployment
metadata:
  name: github_action
  labels:
    app: github_action
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github_action
  template:
    metadata:
      labels:
        app: github_action
    spec:
      containers:
        - name: github_action
          image: "398081196462.dkr.ecr.ca-central-1.amazonaws.com/github_action:1.0"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080