# This is a basic workflow to help you get started with Actions

name: Nodejs app deploy to EKS cluster
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.24.0'
        id: install
      
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: login to amazon ecr
        id: login-to-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Build, tag and push docker image to amazon ecr
        env:
          REGITSTRY: ${{  steps.login-to-ecr.outputs.registry  }}
          REPOSITORY: github_action
          IMAGE_TAG: 1.0
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGITSTRY/$REPOSITORY:$IMAGE_TAG

      - name: update kube config
        run: aws eks update-kubeconfig --name github_action
        
      - name: deploy to eks
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

          

